CREATE TABLE IF NOT EXISTS mock_data (
    mock_data_key BIGSERIAL PRIMARY KEY,
    id TEXT NOT NULL,
    customer_first_name TEXT NOT NULL,
    customer_last_name TEXT NOT NULL,
    customer_age TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    customer_country TEXT NOT NULL,
    customer_postal_code TEXT,
    customer_pet_type TEXT NOT NULL,
    customer_pet_name TEXT NOT NULL,
    customer_pet_breed TEXT NOT NULL,
    seller_first_name TEXT NOT NULL,
    seller_last_name TEXT NOT NULL,
    seller_email TEXT NOT NULL,
    seller_country TEXT NOT NULL,
    seller_postal_code TEXT,
    product_name TEXT NOT NULL,
    product_category TEXT NOT NULL,
    product_price TEXT NOT NULL,
    product_quantity TEXT NOT NULL,
    sale_date TEXT NOT NULL,
    sale_customer_id TEXT NOT NULL,
    sale_seller_id TEXT NOT NULL,
    sale_product_id TEXT NOT NULL,
    sale_quantity TEXT NOT NULL,
    sale_total_price TEXT NOT NULL,
    store_name TEXT NOT NULL,
    store_location TEXT NOT NULL,
    store_city TEXT NOT NULL,
    store_state TEXT,
    store_country TEXT NOT NULL,
    store_phone TEXT NOT NULL,
    store_email TEXT NOT NULL,
    pet_category TEXT NOT NULL,
    product_weight TEXT NOT NULL,
    product_color TEXT NOT NULL,
    product_size TEXT NOT NULL,
    product_brand TEXT NOT NULL,
    product_material TEXT NOT NULL,
    product_description TEXT NOT NULL,
    product_rating TEXT NOT NULL,
    product_reviews TEXT NOT NULL,
    product_release_date TEXT NOT NULL,
    product_expiry_date TEXT NOT NULL,
    supplier_name TEXT NOT NULL,
    supplier_contact TEXT NOT NULL,
    supplier_email TEXT NOT NULL,
    supplier_phone TEXT NOT NULL,
    supplier_address TEXT NOT NULL,
    supplier_city TEXT NOT NULL,
    supplier_country TEXT NOT NULL
);
